title: Salesforce BT Apex Style Guide
email: brian.asher@salesforce.com
description: > # Defines an open source set of coding standards for the Apex programming language.
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
